### ISSUE TITLE
Body has a margin of 8px, you want to set it to 0px

### ISSUE THREAD

**Issue by jzhu01** [TetiLy/prj-rev-bwfs-tea-cozy#1]
I noticed your code is off a bit - it seems like this is because the body has an automatic margin of 8px, so you want to specify it's 0px. :) 

See line: https://github.com/TetiLy/prj-rev-bwfs-tea-cozy/blob/master/TeaCozy/resources/css/style.css#L1-L9

**Comment by TetiLy** [comment]
thanx, I saw it myself, but could not determine the reason.
